portfolio/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "top#index"
  resources :posts do
    resources :ratings
  end
  resources :top
  resources :users
  
end

portfolio/app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_one_attached :image
    has_many :ratings, dependent: :destroy
    
    accepts_nested_attributes_for :ratings

    validates :title, presence: true
    validates :content, presence: true
    validates :user, presence: true
end

portfolio/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :correct_user, only: [:edit, :destroy]
  
    def index
      @posts = Post.includes(:user, :ratings).all
    end
  
    def new
      @post = Post.new
      @post.ratings.build 
    end
  
    def create
        @post = Post.new(post_params)
        @post.user = current_user 

        @post.ratings.each { |rating| rating.user = current_user }
        
        
        if @post.save
          flash[:notice] = "投稿完了"
          redirect_to posts_path
        else
          flash.now[:danger] = "すべての項目に入力してください"
          render :new
        end
    end
  
    def show
      @post = Post.find(params[:id])
    end
  
    def edit
      @post = Post.find(params[:id])
    end
  
    def update
      @post = Post.find(params[:id])
      if @post.update(post_params)
        redirect_to @post
      else
        render :edit
      end
    end
  
    def destroy
      @post = Post.find(params[:id])
      @post.destroy
      redirect_to posts_path
    end
  
    private
  
    def post_params
      params.require(:post).permit(:title, :content, :image, ratings_attributes: [:id, :value])
    end

    def correct_user
      @post = current_user.posts.find_by(id:params[:id])
      unless @post 
        redirect_to posts_path
      end
    end

end

portfolio/app/helpers/posts_helper.rb
module PostsHelper
end

portfolio/app/views/posts/edit.html.erb
<%= stylesheet_link_tag "posts_edit.css", media: "all" %>



<h1>編集画面</h1>
<div class="edit-list">
    <%= form_with model: @post do |form| %>
    <div class="new_title">
        <%= form.label :住所 %>
        <%= form.text_field :title %>
    </div>
    <div class="new_content">
        <%= form.label :コメント %>
        <%= form.text_area :content %>
    </div>
    <div class="new_rating">
        <%= form.fields_for :ratings do |rating_form| %>
        <%= rating_form.label :value, "星評価" %>
        <%= rating_form.select :value, 1..5 %>
        <% end %>
    </div>
    <div class="new_submit">
        <%= form.submit %>
    </div>
    <% end %>
</div>
<div class="back-link">
  <%= link_to "戻る", post_path %>
</div>

portfolio/app/views/posts/index.html.erb
<head>
  <%= stylesheet_link_tag "posts_index.css", media: "all" %>
  <%= stylesheet_link_tag "leaflet.css", media: "all" %>
  <script src="../app/assets/leaflet/leaflet.js"></script>

</head>


<body>
    <div class="post-list">
        <% @posts.each do |post| %>
            <%= link_to post_path(post), class: "post-link" do %>
                <div class="post-item">
                    <h3>投稿ID:<%= post.id %>|ユーザーネーム:<%=post.user.username%></h3>
                    <h2>住所・場所</h2>
                    <span class="post-title"><%= post.title %></span>
                    <h2>評価</h2>
                    <% post.ratings.each do |rating| %>
                        <p>⭐️<%= rating.value %></p>
                    <% end %>
                    
                    <% if post.image.attached? %>
                        <h2>画像</h2>
                        <%= image_tag post.image %>
                    <% end %>

                    <% if post.user == current_user %>
                        <%= button_to "削除", post_path(post), method: :delete, class: "delete-button" %>
                    <% end %>

                </div>
            <% end %>
        <% end %>
    </div>
</body>
<div class="leaflet-container" data-controller="map" data-target="map.placeholder" style="height: 500px; width: 500px;"></div>

portfolio/app/views/posts/new.html.erb
<%= stylesheet_link_tag "posts_new.css", :media => "all" %>
<h1>新規投稿画面</h1>

<% if flash.now[:danger] %>
      <div class="alert alert-danger">
        <%= flash.now[:danger] %>
      </div>
<% end %>

<div class="new-form">
  <%= form_with model: @post do |form| %>
    <div class="new_title">
      <%= form.label :場所  %>
      <%= form.text_field :title %>
    </div>
    <div class="new_image">
      <%= form.label :画像 %>
      <%= form.file_field :image, accept: "image/*" %>
    </div>
    <div class="new_content">
      <%= form.label :詳細 %>
      <%= form.text_area :content %>
    </div>
    
    <div class="new_rating">
      <%= form.fields_for :ratings do |rating_form| %>
          <%= rating_form.label :value, "星評価" %>
          <%= rating_form.select :value, 1..5 %>
      <% end %>
    </div>

  <div class="new_submit">
    <%= form.submit "投稿" %>
  </div>

  <% end %>
</div>
<div class="back-link">
    <%= link_to "Back", posts_path %>
</div>

portfolio/app/views/posts/show.html.erb
<%= stylesheet_link_tag "posts_show.css", :media => "all" %>

<div class="show-list">
  <% if @post.user == current_user %>
    <%= link_to user_path(@post.user), class: "user-link" do %>
      <h3>投稿ID: <%= @post.id %> | ユーザーネーム: <%= @post.user.username %></h3>
    <% end %>
  <% else %>
    <h3>ID: <%= @post.id %> | ユーザーネーム: <%= @post.user.username %></h3>
  <% end %>

  <h1><%= @post.title %></h1>

  <% if @post.ratings.any? %>
    <% @post.ratings.each do |rating| %>
      <h2>評価 ※(⭐️1~⭐️5)</br>⭐️<%= rating.value %></h2>
    <% end %>
  <% else %>
    <p>まだ評価はありません。</p>
  <% end %>

  <h2>コメント</h2>
  <p><%= @post.content %></p>

  <% if @post.image.attached? %>
    <h2>画像</h2>
    <%= image_tag @post.image %>
  <% end %>

<div class="links">
  <div class ="edit-link">
    <% if @post.user == current_user %>
        <%= link_to "編集", edit_post_path(@post) %>
    <% end %>
  </div>

  <div class="back-link">
    <%= link_to "戻る", posts_path %>
  </div>
</div>