portfolio/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "top#index"
  resources :posts do
    resources :ratings
  end
  resources :top
  resources :users
  
end

portfolio/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Board</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css">
  </head>

  <body>
    <header>
      <h1>
        <%= link_to "投稿一覧", posts_path, class: "index-post-link" %>
        <% if user_signed_in? %>
          <span> | </span><%= link_to "新規投稿", new_post_path, class: "new-post-link" %><span> | </span>

          <% if @user==current_user %>
            <%= link_to "ユーザー編集", edit_user_path(@user), class: "edit-user-link" %>
          <% end %>
        <% end %>
      </h1>
      <% if user_signed_in? %>
      <h1><%= button_to "ログアウト",  destroy_user_session_path , class: "logout-link", method: :delete %></h1>
      <% else %>
      <%= link_to "ログイン", new_user_session_path, class:"login-link" %>
      <% end %>
    </header>

    <main>
      <% flash.each do |message_type, message| %>
        <div class="flash_message <%= message_type %>"><%= message %></div>
      <% end %>
      
      <%= yield %>
    </main>
  </body>
</html>